### PR TITLE
Pr update to new rtrlib api

### PR DESCRIPTION
**Pull request by smlng**
this PR address issue #6 and updates rtr_mgr_init calls to match new RTRlib API and also adds cmake modules to find dependencies, such as `libssh`, and `rtrlib`.

This is WIP, as I haven't tested it against/with a _real_ BIRD instance.

### CODE REVIEW

**Comment by waehlisch** [comment]
I get a memory exception. You can check on 141.22.28.223 /prog/....

**Comment by smlng** [comment]
fixed input params, now it's working as far as I can test it.

**Comment by waehlisch** [comment]
Thanks @smlng! Why was RTR_INVALID_PARAM not firing?

**Comment by smlng** [comment]
Oh it was, later on - but first I had to fix a minor memory leak in the config param parser 😄

Though, I was able to run a simple connection test with a BIRD instance (which succeeded), do we know someone with a more production-like setup for testing? Just to be certain, everything is working.

**Pull request merged**
